package jogo.logica;

public enum JogoSituacao {
    AGUARDA_CONFIGURACAO, AGUARDA_DECISAO_MJ, AGUARDA_DECISAO_PE, AGUARDA_JOGADA_ESPECIAL
    , AGUARDA_JOGADA_HUMANA, FIM_JOGO, VER_JOGADA_MAQUINA, MINI_JOGO_CONTAS, MINI_JOGO_PALAVRAS,REPLAY
}
